---
# vars file for openjdk
java:
  openjdk8:
    url: https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jdk_x64_linux_hotspot_8u312b07.tar.gz
    file_name: OpenJDK8U-jdk_x64_linux_hotspot_8u312b07.tar.gz
    path: jdk8u312-b07