---
# tasks file for openjdk
- name: Download Adopt Open JDK 
  get_url: 
    url: "{{ java[java_version].url }}"
    dest: /opt 
    validate_certs: no
    mode: 0755

- name: Create a Directory "{{ dir }}/{{ java[java_version].path }}"
  file:
    path: "{{ dir }}/{{ java[java_version].path }}"
    state: directory
    mode: 0755

- name: Extract "{{ java[java_version] }} into {{ dir }}/{{ java[java_version].path }}"
  ansible.builtin.unarchive:
    src: "/opt/{{ java[java_version].file_name }}"
    dest: "{{ dir }}/{{ java[java_version].path }}"
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ dir }}/{{ java[java_version].path }}"
    dest: "{{ dir }}/jdk"
    state: link
