# This is a basic workflow to help you get started with Actions.

name: Destroy Environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch.
  #workflow_run:
    #types:
    #  - completed
    #workflows:
    #  - "Pre Commit Check"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "terraformBuild"
  terraformDestroy:
    #if: ${{ github.event.workflow_run.conclusion == 'success'}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.0.9 # the version of Terraform you want to install
      TERRAFORM_PATH: . # The Path to the Terraform configuration
      TF_VAR_ansible_pass: ${{ secrets.ANSIBLE_PASS }}
      TF_VAR_ansible_user: ${{ secrets.ANSIBLE_USER }}
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_tenant_id : ${{ secrets.TENANT_ID }}
      ANSIBLE_FORCE_COLOR: '1'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Validate Terraform has installed 
      - name: Terraform Destroy
        id: install_validate
        run: terraform destroy -auto-approve